#!/bin/sh

files=("comcast.txt" "t-mobile.txt" "verizon.txt")
topics=("Downlink" "Uplink")

mkdir output
rm output/*

for file in "${files[@]}"
do
    for topic in "${topics[@]}"
    do
        echo "$topic $file"
        file_name="output/$topic-$file.txt"
        grep $topic $file | awk '{print $3}' > "$file_name"
        csv_name="output/$topic-$file.csv"
        echo "$file_name"
#        paste -d, "$file_name" > "$csv_name"
        
#        grep $topic $file | awk '{print $3}' > "$topic-$file.txt"        
    done
done
