title: "Festina Lente"
subtitle: "Make haste, slowly"
email: peter@petereddy.com
description: >- # this means to ignore newlines until "baseurl:"
  Stuff I think about, mostly harmless
url: "https://petereddy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: petereddy
github_username:  petereddy
#logo: "assets/images/MauroMotion_logo_v002.png"
github: [metadata]

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "air"contrast", "aqua", "dirt", "sunrise", "dark", "default", "neon", "plum", "mint"
search: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name             : "Peter Eddy"
  avatar           : "assets/images/bio-photo.jpeg"
  bio              : "Software butters my bread"
  location         : "Boston, MA"
  email            : 
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:peter@petereddy.net"
    - label: "Portfolio"
      icon: "fab fa-behance-square"
      #url: "https://mauromotion.com"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      #url: "https://mograph.social/@mauro"
    - label: "Reddit"
      icon: "fab fa-reddit"
      #url: "https://www.reddit.com/user/mauro_mograph"
    
    
include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
  # _now_archive
  - scope:
      path: ""
      type: now
    values:
      layout: single
      author_profile: false
      share: true
      show_date: false
      
# Collections
collections:
  now:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/

footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://mograph.social/@mauro"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

